import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const heroSlider = readFileSync(resolve(projectRoot, 'src/components/HeroSlider.vue'), 'utf8')

assert.match(heroSlider, /value: '7\/7'/)
assert.match(heroSlider, /label: 'без выходных'/)
assert.match(heroSlider, /hero-ornamental-pattern-v2\.webp/)
assert.match(heroSlider, /hero-ornamental-gate-v2\.webp/)
assert.match(heroSlider, /hero-wrought-iron-fence-v2\.webp/)
assert.match(heroSlider, /:srcset="slide\.srcset"/)
assert.match(heroSlider, /sizes="100vw"/)
assert.match(heroSlider, /hero-ornamental-pattern-v2-768w\.webp 768w/)
assert.match(heroSlider, /hero-ornamental-pattern-v2-1200w\.webp 1200w/)
assert.match(heroSlider, /:fetchpriority="i === 0 \? 'high' : undefined"/)
assert.match(heroSlider, /v-for="\{ slide, index: i \} in renderedSlides"/)
assert.match(heroSlider, /const renderedSlides = computed/)
assert.match(heroSlider, /previousSlideIndex/)
assert.match(heroSlider, /SLIDE_TRANSITION_CLEANUP_DELAY = 1100/)
assert.match(heroSlider, /setCurrentSlide\(current\.value \+ 1\)/)
assert.match(heroSlider, /FIRST_AUTOPLAY_DELAY = 9000/)
assert.match(heroSlider, /HERO_MOTION_DELAY = 3000/)
assert.match(heroSlider, /window\.setTimeout/)
assert.match(heroSlider, /prefers-reduced-motion: reduce/)
assert.match(heroSlider, /hero-light-sweep/)
assert.match(heroSlider, /hero-pattern/)
assert.match(heroSlider, /\.is-hero-motion-ready \.hero-pattern/)
assert.match(heroSlider, /\.is-hero-motion-ready \.hero-light-sweep/)
assert.match(heroSlider, /hero-image-breathe/)
assert.match(heroSlider, /heroPatternDrift/)
assert.match(heroSlider, /heroImageBreathe/)
assert.match(heroSlider, /@mouseenter="pauseForPointer"/)
assert.match(heroSlider, /@focusin="pauseForFocus"/)
assert.match(heroSlider, /:class="\{ 'is-running': isAutoPlayRunning \}"/)
assert.match(heroSlider, /:title="autoPlayLabel"/)
assert.match(heroSlider, /@click\.stop="toggleAutoPlay"/)
assert.match(heroSlider, /toggleAutoPlay/)
assert.match(heroSlider, /autoplayRing/)
assert.match(heroSlider, /closest\?\.\('\.autoplay-toggle'\)/)
assert.doesNotMatch(heroSlider, /7\/6/)
assert.doesNotMatch(heroSlider, /hero-ornamental-pattern-v2\.png/)
assert.doesNotMatch(heroSlider, /autoPlayText/)
assert.doesNotMatch(heroSlider, /setInterval/)
assert.doesNotMatch(heroSlider, /v-for="\(slide, i\) in slides"/)
assert.doesNotMatch(heroSlider, /mix-blend-mode/)
assert.doesNotMatch(heroSlider, /hero-zoom/)
assert.doesNotMatch(heroSlider, /kenBurns/)
